title:            Nadeem Muhammad
description:      Frontend Engineer | React & TypeScript Specialist

url:
baseurl:

author:
  name:           'Nadeem Muhammad'
  url:            https://linkedin.com/in/nadeem-muhammad

paginate:         5
